<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="default.aspx.cs" Inherits="ayzhuangxiu.news.view._default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="../style.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">
        <asp:Literal ID="ltHeader" runat="server"></asp:Literal>
        <div class="container">
            <div style="padding: 30px; border: solid 1px #CCC; margin: 20px 0px;">
                <div style="padding: 10px 0px; padding-top: 20px; font-size: 16px;">
                    <strong>箭牌橱柜揭秘厨房最美角落</strong>
                </div>
                <div style="min-height: 200px; height: auto; _height: 200px; padding: 10px;">
                    <p>
                    </p>
                    <p style="PADDING-BOTTOM: 0px; WIDOWS: 1; TEXT-TRANSFORM: none; TEXT-INDENT: 28px; MARGIN: 0px 0px 15px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/21px Arial, 微软雅黑; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(56,56,56); WORD-SPACING: 0px; PADDING-TOP: 0px; font-stretch: normal; -webkit-text-stroke-width: 0px"><span style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 18px/1.5 'times new roman'; PADDING-TOP: 0px; font-stretch: normal">厨房是家的最重要组成部分，很多人会为厨房装修而头疼，担心空间利用不足，担心家电没地放，还担心装修效果不好看！确实，在靓丽的厨房里面做饭，相信幸福指数也会上升。下面跟着箭牌橱柜一起看看厨房这些美丽角落吧。</span></p>
                    <p style="PADDING-BOTTOM: 0px; WIDOWS: 1; TEXT-TRANSFORM: none; TEXT-INDENT: 28px; MARGIN: 0px 0px 15px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/21px Arial, 微软雅黑; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(56,56,56); WORD-SPACING: 0px; PADDING-TOP: 0px; font-stretch: normal; -webkit-text-stroke-width: 0px"></p>
                    <p style="PADDING-BOTTOM: 0px; WIDOWS: 1; TEXT-TRANSFORM: none; TEXT-INDENT: 28px; MARGIN: 0px 0px 15px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/21px Arial, 微软雅黑; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(56,56,56); WORD-SPACING: 0px; PADDING-TOP: 0px; font-stretch: normal; -webkit-text-stroke-width: 0px"><span style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 18px/1.5 'times new roman'; PADDING-TOP: 0px; font-stretch: normal">有时候，“美”不等同于花俏，箭牌橱柜维纳斯，揉合时尚与高雅设计，告别暗沉色调，采用柔和、细腻而统一的淡雅基调。连带油烟机脱离了沉闷黑色，米白色的实木“外套”，两棵翠绿的植物，耀眼的阳光，打造出美观而又实用的角落。</span></p>
                    <p style="TEXT-ALIGN: center; PADDING-BOTTOM: 0px; WIDOWS: 1; TEXT-TRANSFORM: none; TEXT-INDENT: 0em; MARGIN: 0px 0px 15px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/1.8 Arial, 微软雅黑; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(56,56,56); WORD-SPACING: 0px; PADDING-TOP: 0px; font-stretch: normal; -webkit-text-stroke-width: 0px">
                        <img style="BORDER-BOTTOM: rgb(255,255,255); BORDER-LEFT: rgb(255,255,255); PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/1.5 Arial, 微软雅黑; FLOAT: none; VERTICAL-ALIGN: top; BORDER-TOP: rgb(255,255,255); BORDER-RIGHT: rgb(255,255,255); PADDING-TOP: 0px; font-stretch: normal" title="箭牌橱柜维纳斯.jpg" src="http://www.arrowkitchen.cn/kps01/M00/0A/01/wKiAiVhYxESRjMtbAACVDBFNFis147.jpg">
                    </p>
                    <p style="TEXT-ALIGN: center; PADDING-BOTTOM: 0px; WIDOWS: 1; TEXT-TRANSFORM: none; TEXT-INDENT: 0em; MARGIN: 0px 0px 15px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/21px Arial, 微软雅黑; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(56,56,56); WORD-SPACING: 0px; PADDING-TOP: 0px; font-stretch: normal; -webkit-text-stroke-width: 0px"><span style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 18px/1.5 'times new roman'; COLOR: red; PADDING-TOP: 0px; font-stretch: normal">箭牌橱柜维纳斯</span></p>
                    <p style="PADDING-BOTTOM: 0px; WIDOWS: 1; TEXT-TRANSFORM: none; TEXT-INDENT: 28px; MARGIN: 0px 0px 15px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/21px Arial, 微软雅黑; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(56,56,56); WORD-SPACING: 0px; PADDING-TOP: 0px; font-stretch: normal; -webkit-text-stroke-width: 0px"><span style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 18px/1.5 'times new roman'; PADDING-TOP: 0px; font-stretch: normal">黄香檀色的吧台搭配不锈钢台架，精致的金属配件更显其时尚气质。闲暇的午后坐在吧台上看看书，站在吧台旁喝杯咖啡，惬意无比。明艳的黄香檀色门板表面纹理略显交错，好像拉直的年轮，犹如史官一般记录着美好生活的点滴。静谧的角落，感受惬意的暖阳，体验淡然的喜乐生活。</span></p>
                    <p style="TEXT-ALIGN: center; PADDING-BOTTOM: 0px; WIDOWS: 1; TEXT-TRANSFORM: none; TEXT-INDENT: 0em; MARGIN: 0px 0px 15px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/21px Arial, 微软雅黑; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(56,56,56); WORD-SPACING: 0px; PADDING-TOP: 0px; font-stretch: normal; -webkit-text-stroke-width: 0px">
                        <span style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/1.5 Arial, 微软雅黑; COLOR: red; PADDING-TOP: 0px; font-stretch: normal">
                            <img style="BORDER-BOTTOM: rgb(255,255,255); BORDER-LEFT: rgb(255,255,255); PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/1.5 Arial, 微软雅黑; FLOAT: none; VERTICAL-ALIGN: top; BORDER-TOP: rgb(255,255,255); BORDER-RIGHT: rgb(255,255,255); PADDING-TOP: 0px; font-stretch: normal" title="箭牌橱柜香榭园.jpg" src="http://www.arrowkitchen.cn/kps01/M00/0A/01/wKiAiVhYxGi_xf0xAAC7KX3lC04876.jpg"><br style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/1.5 Arial, 微软雅黑; PADDING-TOP: 0px; font-stretch: normal">
                        </span>
                    </p>
                    <p style="TEXT-ALIGN: center; PADDING-BOTTOM: 0px; WIDOWS: 1; TEXT-TRANSFORM: none; TEXT-INDENT: 0em; MARGIN: 0px 0px 15px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/21px Arial, 微软雅黑; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(56,56,56); WORD-SPACING: 0px; PADDING-TOP: 0px; font-stretch: normal; -webkit-text-stroke-width: 0px"><span style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 18px/1.5 'times new roman'; COLOR: red; PADDING-TOP: 0px; font-stretch: normal">箭牌橱柜香榭园</span></p>
                    <p style="PADDING-BOTTOM: 0px; WIDOWS: 1; TEXT-TRANSFORM: none; TEXT-INDENT: 28px; MARGIN: 0px 0px 15px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/21px Arial, 微软雅黑; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(56,56,56); WORD-SPACING: 0px; PADDING-TOP: 0px; font-stretch: normal; -webkit-text-stroke-width: 0px"><span style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 18px/1.5 'times new roman'; PADDING-TOP: 0px; font-stretch: normal">柔和的灯光下，象牙白色门板的天然质感古典时尚，仿古描边线精致优美；铜条、清玻相互辉映。跟爱人在这里聊天谈情，一杯咖啡，一朵小花，静静地对望，让心情跟着平静，渐渐飞扬。</span></p>
                    <p style="TEXT-ALIGN: center; PADDING-BOTTOM: 0px; WIDOWS: 1; TEXT-TRANSFORM: none; TEXT-INDENT: 0em; MARGIN: 0px 0px 15px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/21px Arial, 微软雅黑; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(56,56,56); WORD-SPACING: 0px; PADDING-TOP: 0px; font-stretch: normal; -webkit-text-stroke-width: 0px">
                        <span style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/1.5 Arial, 微软雅黑; COLOR: red; PADDING-TOP: 0px; font-stretch: normal">
                            <img style="BORDER-BOTTOM: rgb(255,255,255); BORDER-LEFT: rgb(255,255,255); PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/1.5 Arial, 微软雅黑; FLOAT: none; VERTICAL-ALIGN: top; BORDER-TOP: rgb(255,255,255); BORDER-RIGHT: rgb(255,255,255); PADDING-TOP: 0px; font-stretch: normal" title="箭牌橱柜莎特曼庄园.jpg" src="http://www.arrowkitchen.cn/kps01/M00/0A/01/wKiAiVhYxHj0B8PiAACAMJHacmk723.jpg"><br style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/1.5 Arial, 微软雅黑; PADDING-TOP: 0px; font-stretch: normal">
                        </span>
                    </p>
                    <p style="TEXT-ALIGN: center; PADDING-BOTTOM: 0px; WIDOWS: 1; TEXT-TRANSFORM: none; TEXT-INDENT: 0em; MARGIN: 0px 0px 15px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/21px Arial, 微软雅黑; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(56,56,56); WORD-SPACING: 0px; PADDING-TOP: 0px; font-stretch: normal; -webkit-text-stroke-width: 0px"><span style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 18px/1.5 'times new roman'; COLOR: red; PADDING-TOP: 0px; font-stretch: normal">箭牌橱柜莎特曼庄园</span></p>
                    <p style="PADDING-BOTTOM: 0px; WIDOWS: 1; TEXT-TRANSFORM: none; TEXT-INDENT: 28px; MARGIN: 0px 0px 15px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/21px Arial, 微软雅黑; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(56,56,56); WORD-SPACING: 0px; PADDING-TOP: 0px; font-stretch: normal; -webkit-text-stroke-width: 0px"><span style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 18px/1.5 'times new roman'; PADDING-TOP: 0px; font-stretch: normal">银灰色的橱柜，气质又舒适。简约的功能设计，略显调皮的搁板，智能的电动卷帘门，刚与柔结合得恰到好处。光线透过清风吹拂的窗帘投进室内，感受大自然的和煦微风和温暖阳光，尽情享受智能化的厨房体验。别致而独特的角落设计让做饭的时光也变得额外美丽。</span></p>
                    <p style="TEXT-ALIGN: center; PADDING-BOTTOM: 0px; WIDOWS: 1; TEXT-TRANSFORM: none; TEXT-INDENT: 0em; MARGIN: 0px 0px 15px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/21px Arial, 微软雅黑; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(56,56,56); WORD-SPACING: 0px; PADDING-TOP: 0px; font-stretch: normal; -webkit-text-stroke-width: 0px">
                        <span style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/1.5 Arial, 微软雅黑; COLOR: red; PADDING-TOP: 0px; font-stretch: normal">
                            <img style="BORDER-BOTTOM: rgb(255,255,255); BORDER-LEFT: rgb(255,255,255); PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/1.5 Arial, 微软雅黑; FLOAT: none; VERTICAL-ALIGN: top; BORDER-TOP: rgb(255,255,255); BORDER-RIGHT: rgb(255,255,255); PADDING-TOP: 0px; font-stretch: normal" title="箭牌橱柜灵动空间.jpg" src="http://www.arrowkitchen.cn/kps01/M00/0A/01/wKiAiVhYxIT1WghJAABi3F3FrwA648.jpg"><br style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/1.5 Arial, 微软雅黑; PADDING-TOP: 0px; font-stretch: normal">
                        </span>
                    </p>
                    <p style="TEXT-ALIGN: center; PADDING-BOTTOM: 0px; WIDOWS: 1; TEXT-TRANSFORM: none; TEXT-INDENT: 0em; MARGIN: 0px 0px 15px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/21px Arial, 微软雅黑; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(56,56,56); WORD-SPACING: 0px; PADDING-TOP: 0px; font-stretch: normal; -webkit-text-stroke-width: 0px"><span style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 18px/1.5 'times new roman'; COLOR: red; PADDING-TOP: 0px; font-stretch: normal">箭牌橱柜灵动空间</span></p>
                    <p style="TEXT-ALIGN: center; PADDING-BOTTOM: 0px; WIDOWS: 1; TEXT-TRANSFORM: none; TEXT-INDENT: 28px; MARGIN: 0px 0px 15px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/21px Arial, 微软雅黑; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(56,56,56); WORD-SPACING: 0px; PADDING-TOP: 0px; font-stretch: normal; -webkit-text-stroke-width: 0px"></p>
                    <p style="PADDING-BOTTOM: 0px; WIDOWS: 1; TEXT-TRANSFORM: none; TEXT-INDENT: 28px; MARGIN: 0px 0px 15px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/21px Arial, 微软雅黑; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(56,56,56); WORD-SPACING: 0px; PADDING-TOP: 0px; font-stretch: normal; -webkit-text-stroke-width: 0px"><span style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 18px/1.5 'times new roman'; PADDING-TOP: 0px; font-stretch: normal">每一人都应为自己的家准备一个这样的角落，不用太大，却深得我们心。安抚我们烦恼杂乱的心灵，在这个角落，放松自己，舒畅身心。</span></p>
                    <p style="PADDING-BOTTOM: 0px; WIDOWS: 1; TEXT-TRANSFORM: none; TEXT-INDENT: 28px; MARGIN: 0px 0px 15px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT: 14px/21px Arial, 微软雅黑; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(56,56,56); WORD-SPACING: 0px; PADDING-TOP: 0px; font-stretch: normal; -webkit-text-stroke-width: 0px"></p>
                    <br class="Apple-interchange-newline">
                    <br>
                    <p></p>

                </div>
                <div class="clear"></div>
            </div>
        </div>
        <asp:Literal ID="ltFooter" runat="server"></asp:Literal>
    </form>
</body>
</html>
